### ISSUE TITLE
Relationship with vidstream.to

### ISSUE THREAD

**Issue by Datsuke** [aalykiot/vidstream#1]
@aalykiot 
Hello!

I've been looking to report a few bugs I've found for vidstream.to, however for literally months now I haven't being able to get any sort of contact or support ticket information, this has been the closest thing I've found so far. 

Apologies in advance in case this is an unrelated project.

Thank you!

**Comment by aalykiot** [comment]
Hello, @Datsuke! 

This is a personal side project of mine just to experiment with some technologies. So totally unrelated to `vidstream.to`.
